name: deploy-elasticbeanstalk

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - './**'

jobs:
  buid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Client
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Build Server
        working-directory: ./server
        run: |
          npm install
          npm run build

      - name: Create Deploy Package
        working-directory: ./server
        run: zip -r deploy.zip ./.ebextensions/ ./dist/ ./client/ ./config/ ./package.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APP }}
          environment_name: ${{ secrets.AWS_EB_ENV }}
          version_label: ${{ secrets.AWS_EB_APP }}-deploy-instance-${{ github.run_id }}.${{ github.run_number }}
          region: eu-west-1
          deployment_package: ./server/deploy.zip
